# Generated by Django 4.1.7 on 2023-05-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the singer', upload_to='singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the song', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(null=True, upload_to='songs'),
        ),
    ]
