# Generated by Django 4.1.6 on 2023-05-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_favourites_alter_song_image_and_more'),
    ]

    operations = [
    ]
