# Generated by Django 4.1.7 on 2023-05-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_singer_image_alter_song_image_alter_song_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
