# Generated by Django 4.1.6 on 2023-05-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_singer_image_alter_song_image_alter_song_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Song'},
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
