# Generated by Django 4.1.7 on 2023-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_time_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
