# Generated by Django 4.1.6 on 2023-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_news_alter_song_image_alter_song_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(blank=True, help_text='The image of the song', upload_to='images')),
                ('news', models.CharField(max_length=200)),
            ],
        ),
    ]
