# Generated by Django 4.1.7 on 2023-05-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
