# Generated by Django 4.1.7 on 2023-05-14 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0007_playlist_playlistsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
