# Generated by Django 4.1.7 on 2023-05-14 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_remove_playlistsong_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorites',
        ),
        migrations.AddField(
            model_name='song',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
