# Generated by Django 4.1.7 on 2023-05-14 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_remove_song_favorites_song_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favourites',
        ),
        migrations.AddField(
            model_name='song',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
