# Generated by Django 4.1.7 on 2023-05-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_remove_song_favourites_song_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
